  - name: Update Ubuntu
    apt:
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian" 

  - name: Update Rocky
    yum:
      update_cache: yes
    when: ansible_facts['os_family'] == "RedHat"