    - name: Install MariaDB and python complement on Ubuntu
      apt:
        name: 
          - mariadb-server
          - python3-pymysql
        state: latest
      when: ansible_facts['os_family'] == "Debian"

    - name: Install MariaDB and python complement on Rocky
      package:
        name: 
          - mariadb-server
          - python3
        state: latest
      notify:
<<<<<<< HEAD:roles/installMariaDB/tasks/main.yml
       - startMariaDB
=======
       - handlers/startMariaDB
>>>>>>> 6eb005591a66989e06403c2ca91788ab29f2e285:roles/installMariaDB/tasks/installMariaDB.yaml
      when: ansible_facts['os_family'] == "RedHat"

    - name:  Install pymysql on Rocky
      become: true
      pip: 
        name: pymysql
        state: present
      when: ansible_facts['os_family'] == "RedHat"