  - name: Create Database "{{ database_name }}" on Ubuntu
    mysql_db:
       login_unix_socket: /var/run/mysqld/mysqld.sock
       name: "{{ database_name }}"
       state: present
    when: ansible_facts['os_family'] == "Debian"
  
  - name: Create Database "{{ database_name }}" on Rocky
    mysql_db:
       login_unix_socket: /var/lib/mysql/mysql.sock
       name: "{{ database_name }}"
       state: present
    when: ansible_facts['os_family'] == "RedHat"