---
- name: Install services for mailling
  hosts: mailservers
  become: yes
  
  tasks: 
  - name: Update
    apt:
      update_cache: yes

  - name: Install postfix
    apt: 
      name: postfix
      state: present

  - name: Install apache2
    apt: 
      name: apache2
      state: latest

  - name: Install dovecot
    apt: 
      name: dovecot-core
      state: latest

  - name: Install zip
    apt: 
      name: zip
      state: latest

  - name: Download squirrelmail
    get_url:
      url: https://www.squirrelmail.org/countdl.php?fileurl=http%3A%2F%2Fprdownloads.sourceforge.net%2Fsquirrelmail%2Fsquirrelmail-webmail-1.4.22.tar.gz
      dest: /home/ansible/

  - name: Unzip squirrelmail
    unarchive:
      src: /home/ansible/squirrelmail-webmail-1.4.22.tar.gz
      dest: /home/ansible/
  
  - name: Move to mail
    copy: remote_src=True src=/home/ansible/squirrelmail-webmail-1.4.22 dest=/var/www/html/mail

  - name: Move configuration file
    copy: remote_src=True src=./config_default.php  dest=/var/www/html/mail/config/config.php

  - name: Change $domain
    lineinfile:
      path: /var/www/html/mail/config/config.php
      regexp: '^\$domain ='
      line: $domain = 'pruebataller.ort';

  - name: Change $data_dir
    lineinfile:
      path: /var/www/html/mail/config/config.php
      regexp: '^\$data_dir'
      line: $data_dir = '/var/www/html/mail/data/';

  - name: Change $attachment
    lineinfile:
      path: /var/www/html/mail/config/config.php
      regexp: '^\$attachment_dir'
      line: $attachment_dir = '/var/www/html/mail/attach/';

  - name: Squirrelmail permissions
    file:
      path: /var/www/html/mail
      state: directory
      recurse: yes
      owner: www-data
      group: www-data
      mode: '0755'