---
- name: 
  hosts: appservers
  become: yes
  
  
  tasks: 
  - name: Update Ubuntu 22.04
    apt:
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian" 

  - name: Update Rocky
    yum:
      update_cache: yes
    when: ansible_facts['os_family'] == "RedHat" 
  
  

  - name: Permit traffic to port 8080 on Ubuntu
    ufw:
      rule: allow
      port: '8080'
    when: ansible_facts['os_family'] == "Debian"

  - name: Permit traffic to port 8080 on Rocky
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
    when: ansible_facts['os_family'] == "RedHat"

  - name: Start and Enable firewalld on Rocky
    systemd:
      name: firewalld
      state: reloaded
      daemon_reload: true
    when: ansible_facts['os_family'] == "RedHat"


  - name: Create directory for Java 1.8 
    file:
      path: /usr/java
      state: directory

  - name: Extract Java 1.8
    unarchive:
      src: /home/ansible/OBL_TSL-2/files/jre-8u321-linux-x64.tar.gz
      dest: /usr/java
  
  - name: Export variable Java 
    command: echo 'export PATH="$PATH:/usr/java/jre1.8.0_321/bin"' >> ~/.bashrc && source ~/.bashrc



  - name: Install MariaDB and python complement on Ubuntu
    apt:
      name: 
        - mariadb-server
        - python3-pymysql
      state: latest
    when: ansible_facts['os_family'] == "Debian"

  - name: Install MariaDB and python complement on Rocky
    package:
      name: 
        - mariadb-server
        - python3
      state: latest
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install pymysql on Rocky
    become: true
    pip: 
      name: pymysql
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Start and Enable mariadb on Rocky
    systemd:
      name: mariadb
      enabled: yes
      state: started
    when: ansible_facts['os_family'] == "RedHat"

  - name: Create database user with name 'tallerlinux' and password 'prueba' with all database privileges
    mysql_user:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: ort
      password: dariogianedgardo
      priv: 'tallerlinux.*:ALL'
      # state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Create database user with name 'tallerlinux' and password 'prueba' with all database privileges
    mysql_user:
      login_unix_socket: /var/lib/mysql/mysql.sock
      name: ort
      password: dariogianedgardo
      priv: 'tallerlinux.*:ALL'
      # state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Create DB for tomcat 
    mysql_db:
       login_unix_socket: /var/run/mysqld/mysqld.sock
       name: tallerlinux
       state: present
    when: ansible_facts['os_family'] == "Debian"
  
  - name: Create DB for tomcat on Rocky
    mysql_db:
       login_unix_socket: /var/lib/mysql/mysql.sock
       name: tallerlinux
       state: present
    when: ansible_facts['os_family'] == "RedHat"
       
  - name: Copy creartablas.sql to remote
    become: true 
    copy: 
      src: /home/ansible/OBL_TSL-2/files/creartablas.sql
      dest: /home/ansible/
      owner: ansible
      group: ansible
      mode: 0744

  - name: Create tables SQL 
    mysql_db: 
      name: tallerlinux 
      state: import 
      target: /home/ansible/creartablas.sql
      login_user: ort
      login_password: dariogianedgardo



  - name: Create a Tomcat User
    user:
      name: tomcat
 
  - name: Create a Tomcat Group
    group:
      name: tomcat

  - name: Extract Tomcat
    unarchive:
      src: /home/ansible/OBL_TSL-2/files/tomcat.tar.gz
      dest: /opt/
      owner: tomcat
      group: tomcat
      mode: 0755

  - name: Rename tomcat folder after to Extract
    command: mv /opt/apache-tomcat-9.0.65 /opt/tomcat

  - name: Change ownership of tomcat directory
    file:
      path: /opt/
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory
 
  - name: Create a /opt/config directory
    file:
      path: /opt/config
      owner: tomcat
      group: tomcat
      mode: 755
      recurse: yes

  - name: Copy app.properties to remote
    become: true 
    copy: 
      src: /home/ansible/OBL_TSL-2/files/app.properties
      dest: /opt/config
      owner: tomcat
      group: tomcat
      mode: 0755

  - name: Copy tomcat.service to remote
    become: true 
    copy: 
      src: /home/ansible/OBL_TSL-2/files/tomcat.service
      dest: /etc/systemd/system/
      owner: tomcat
      group: tomcat
      mode: 0755
 
  - name: Copy todo.war to remote
    become: true 
    copy: 
      src: /home/ansible/OBL_TSL-2/files/todo.war
      dest: /opt/tomcat/webapps/
      owner: tomcat
      group: tomcat
      mode: 0644

  - name: Start and Enable Tomcat 9 on server
    systemd:
      name: tomcat
      state: started
      daemon_reload: true
